name: advnetsci
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - graph-tool
  - scikit-learn
  - numpy
  - numba
  - scipy
  - networkx
  - seaborn
  - matplotlib
  - gensim
  - ipykernel
  - tqdm
  - black
  - faiss
  - ca-certificates
  - openssl
  - jupyter-book
  - python-igraph
  - certifi
  - igraph
  - pandas
  - nbmerge
  - papermill
  - gdown
  - nbconvert
  - pip:
    - jupyterlab_myst

